"""add type column to BiteBase

Revision ID: 608a4aac857b
Revises: 9de61577bbbb
Create Date: 2021-11-12 17:17:28.967753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608a4aac857b'
down_revision = '9de61577bbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bites', sa.Column('type', sa.String(length=20), nullable=True, default='bite'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bites', 'type')
    # ### end Alembic commands ###
